
# Parser_Number_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '79359633C517E839DA2C575ADA9C880E'
    
_lr_action_items = {'ZERO':([0,5,7,14,17,],[1,1,1,17,17,]),')':([1,6,10,11,12,16,],[-7,-6,16,-1,-2,-3,]),'*':([1,3,4,6,10,11,12,16,],[-7,8,9,-6,9,8,9,-3,]),'+':([2,13,15,17,18,19,],[7,-5,-4,-9,-8,-10,]),'(':([0,5,7,],[5,5,5,]),'UNIT':([0,5,7,8,9,],[6,6,6,14,14,]),'$end':([1,4,6,11,12,16,],[-7,0,-6,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'unit':([0,5,7,],[3,3,11,]),'S':([0,5,7,],[4,10,12,]),'zeros':([14,17,],[18,19,]),'multi':([8,9,],[13,15,]),'T':([0,5,7,],[2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> T + unit','S',3,'p_s_1','Number.py',99),
  ('S -> T + S','S',3,'p_s_2','Number.py',105),
  ('S -> ( S )','S',3,'p_s_3','Number.py',111),
  ('T -> S * multi','T',3,'p_t_1','Number.py',118),
  ('T -> unit * multi','T',3,'p_t_2','Number.py',124),
  ('unit -> UNIT','unit',1,'p_unit','Number.py',130),
  ('unit -> ZERO','unit',1,'p_unit','Number.py',131),
  ('multi -> UNIT zeros','multi',2,'p_multi','Number.py',138),
  ('zeros -> ZERO','zeros',1,'p_zeros','Number.py',145),
  ('zeros -> ZERO zeros','zeros',2,'p_zeros','Number.py',146),
]
