
# Parser_Number_2_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'F7269452336BCB7DB71424E0DB417199'
    
_lr_action_items = {'$end':([1,4,6,13,14,16,],[-7,0,-6,-1,-2,-3,]),'UNIT':([0,5,7,8,9,],[6,6,12,6,12,]),'PLUS':([3,11,15,17,18,19,],[8,-5,-4,-8,-9,-10,]),'TIMES':([1,2,4,6,10,13,14,16,],[-7,7,9,-6,9,7,9,-3,]),'(':([0,5,8,],[5,5,5,]),')':([1,6,10,13,14,16,],[-7,-6,16,-1,-2,-3,]),'ZERO':([0,5,8,12,18,],[1,1,1,18,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,5,8,],[4,10,14,]),'zeros':([12,18,],[17,19,]),'unit':([0,5,8,],[2,2,13,]),'T':([0,5,8,],[3,3,3,]),'multi':([7,9,],[11,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> T PLUS unit','S',3,'p_s_1','Number.py',109),
  ('S -> T PLUS S','S',3,'p_s_2','Number.py',116),
  ('S -> ( S )','S',3,'p_s_3','Number.py',123),
  ('T -> S TIMES multi','T',3,'p_t_1','Number.py',130),
  ('T -> unit TIMES multi','T',3,'p_t_2','Number.py',137),
  ('unit -> UNIT','unit',1,'p_unit','Number.py',144),
  ('unit -> ZERO','unit',1,'p_unit','Number.py',145),
  ('multi -> UNIT zeros','multi',2,'p_multi','Number.py',152),
  ('zeros -> ZERO','zeros',1,'p_zeros','Number.py',159),
  ('zeros -> ZERO zeros','zeros',2,'p_zeros','Number.py',160),
]
